namespace FileTime.App.Core.Command
{
    public enum Commands
    {
        CloseTab,
        Copy,
        Cut,
        GoUp,
        MoveCursorDown,
        MoveCursorUp,
        Open,
        Paste,
        Select,
        ToggleHidden,
        CreateContainer,
        CreateElement,
        MoveCursorUpPage,
        MoveCursorDownPage,
        MoveToTop,
        MoveToBottom,
        MoveToFirst,
        MoveToLast,
        GoToRoot,
        GoToProvider,
        GoToHome,
        EnterRapidTravel,
        OpenOrRun,
    }
}